# Generated by Django 6.0.7 on 2026-07-22 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('internal', 'Internal'), ('external', 'External'), ('both', 'Both')], max_length=20)),
                ('date_time', models.DateTimeField()),
                ('venue', models.CharField(max_length=255)),
                ('max_capacity', models.PositiveIntegerField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('organiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
